# Generated by Django 5.2.8 on 2025-11-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
    ]
