# Generated by Django 5.2.8 on 2025-11-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker')], default='employer', max_length=20),
        ),
    ]
