# Generated by Django 5.2.8 on 2025-11-29 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
